/**
 * /admin/pitch-generator — list / launcher view.
 *
 * Server-rendered list of recent PitchRun rows + a "New pitch" CTA. Filters
 * (status, prospect search) are applied via querystring to keep this page a
 * server component (no client fetch waterfall on first paint). Auth is
 * enforced by reading the staff session cookie directly. Anyone SALES_REP+
 * can see the list. ADMIN-only controls live on the detail page, not here.
 *
 * Reads PitchRun + Prospect via $queryRawUnsafe because both tables were
 * added late and downstream code paths still rely on raw access in places
 * (mirrors the pattern in /admin/builders/[id]).
 *
 * Feature flag: NEXT_PUBLIC_FEATURE_PITCH_GENERATOR_ENABLED. When unset or
 * 'false', renders a disabled-state block with link to .env.example.
 */

import Link from 'next/link'
import { redirect } from 'next/navigation'
import { Plus, Search, FileText, Sparkles } from 'lucide-react'
import { prisma } from '@/lib/prisma'
import { getStaffSession } from '@/lib/staff-auth'
import { parseRoles } from '@/lib/permissions'
import { formatDate } from '@/lib/utils'

export const dynamic = 'force-dynamic'
export const revalidate = 0

// Status values must match prisma/schema.prisma PitchRun.status
type PitchRunStatus =
  | 'QUEUED'
  | 'GENERATING'
  | 'PREVIEW'
  | 'APPROVED'
  | 'SENT'
  | 'FAILED'

const STATUS_VALUES: PitchRunStatus[] = [
  'QUEUED',
  'GENERATING',
  'PREVIEW',
  'APPROVED',
  'SENT',
  'FAILED',
]

interface PitchRunRow {
  id: string
  prospectId: string
  companyName: string
  style: string
  layout: string
  status: PitchRunStatus
  costEstimate: number | null
  generatedBy: string | null
  generatedByName: string | null
  createdAt: Date
}

interface SearchParams {
  status?: string
  q?: string
  page?: string
}

const PAGE_SIZE = 50

function statusBadgeClass(status: string): string {
  switch (status) {
    case 'APPROVED':
    case 'SENT':
      return 'bg-emerald-500/15 text-emerald-300 border-emerald-500/30'
    case 'PREVIEW':
      return 'bg-c1/15 text-c1 border-c1/30'
    case 'QUEUED':
    case 'GENERATING':
      return 'bg-amber-500/15 text-amber-300 border-amber-500/30'
    case 'FAILED':
      return 'bg-rose-500/15 text-rose-300 border-rose-500/30'
    default:
      return 'bg-white/10 text-fg-muted border-glass-border'
  }
}

function styleBadgeClass(style: string): string {
  switch (style) {
    case 'HERITAGE':
      return 'bg-amber-700/15 text-amber-200 border-amber-700/30'
    case 'EXECUTIVE':
      return 'bg-slate-500/15 text-slate-200 border-slate-500/30'
    case 'BUILDER_FIELD':
      return 'bg-orange-500/15 text-orange-200 border-orange-500/30'
    default:
      return 'bg-white/10 text-fg-muted border-glass-border'
  }
}

async function fetchPitchRuns(params: SearchParams): Promise<{
  rows: PitchRunRow[]
  total: number
}> {
  const conditions: string[] = []
  const args: unknown[] = []
  let idx = 1

  if (params.status && STATUS_VALUES.includes(params.status as PitchRunStatus)) {
    conditions.push(`pr."status" = $${idx}`)
    args.push(params.status)
    idx++
  }

  if (params.q && params.q.trim()) {
    conditions.push(`p."companyName" ILIKE $${idx}`)
    args.push(`%${params.q.trim()}%`)
    idx++
  }

  const where = conditions.length ? `WHERE ${conditions.join(' AND ')}` : ''
  const page = Math.max(1, parseInt(params.page || '1', 10) || 1)
  const offset = (page - 1) * PAGE_SIZE

  try {
    const countResult: Array<{ total: number }> = await prisma.$queryRawUnsafe(
      `SELECT COUNT(*)::int AS total
       FROM "PitchRun" pr
       JOIN "Prospect" p ON p."id" = pr."prospectId"
       ${where}`,
      ...args
    )
    const total = countResult[0]?.total ?? 0

    const rows: PitchRunRow[] = await prisma.$queryRawUnsafe(
      `SELECT
         pr."id",
         pr."prospectId",
         p."companyName",
         pr."style",
         pr."layout",
         pr."status",
         pr."costEstimate"::float AS "costEstimate",
         pr."generatedBy",
         (s."firstName" || ' ' || s."lastName") AS "generatedByName",
         pr."createdAt"
       FROM "PitchRun" pr
       JOIN "Prospect" p ON p."id" = pr."prospectId"
       LEFT JOIN "Staff" s ON s."id" = pr."generatedBy"
       ${where}
       ORDER BY pr."createdAt" DESC
       LIMIT ${PAGE_SIZE} OFFSET ${offset}`,
      ...args
    )

    return { rows, total }
  } catch {
    return { rows: [], total: 0 }
  }
}

function FeatureFlagOff() {
  return (
    <div className="space-y-6 max-w-3xl">
      <div>
        <h1 className="text-3xl font-bold text-fg">Pitch generator</h1>
        <p className="text-fg-muted mt-2">
          Builder pitch microsites, generated by Claude.
        </p>
      </div>
      <div className="glass-card p-6 border border-glass-border rounded-lg space-y-3">
        <div className="flex items-center gap-2 text-amber-300">
          <Sparkles className="w-4 h-4" />
          <span className="text-sm font-semibold uppercase tracking-wide">
            Disabled
          </span>
        </div>
        <p className="text-fg">
          The pitch generator is gated behind a feature flag.
        </p>
        <p className="text-sm text-fg-muted">
          To enable it, set the following in your environment and redeploy:
        </p>
        <pre className="bg-canvas/60 border border-glass-border rounded-md p-3 text-xs text-fg-muted overflow-x-auto">
          {`NEXT_PUBLIC_FEATURE_PITCH_GENERATOR_ENABLED=true`}
        </pre>
        <p className="text-xs text-fg-muted">
          See <code className="text-c1">.env.example</code> for the full list of
          flags.
        </p>
      </div>
    </div>
  )
}

export default async function PitchGeneratorListPage({
  searchParams,
}: {
  searchParams: Promise<SearchParams>
}) {
  // Feature flag gate (renders pre-auth so disabled state is consistent).
  if (process.env.NEXT_PUBLIC_FEATURE_PITCH_GENERATOR_ENABLED !== 'true') {
    return <FeatureFlagOff />
  }

  const session = await getStaffSession()
  if (!session) {
    redirect('/staff/login?redirect=/admin/pitch-generator')
  }

  const roles = parseRoles(session.roles || session.role)
  const canSee =
    roles.includes('ADMIN') ||
    roles.includes('MANAGER') ||
    roles.includes('SALES_REP')

  if (!canSee) {
    return (
      <div className="text-center py-12 text-fg-muted">
        You do not have permission to view the pitch generator.
      </div>
    )
  }

  const params = await searchParams
  const { rows, total } = await fetchPitchRuns(params)
  const page = Math.max(1, parseInt(params.page || '1', 10) || 1)
  const totalPages = Math.max(1, Math.ceil(total / PAGE_SIZE))

  const activeStatus = params.status || 'ALL'
  const activeQuery = params.q || ''

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-end sm:justify-between gap-4">
        <div>
          <h1 className="text-3xl font-bold text-fg">Pitch generator</h1>
          <p className="text-fg-muted mt-2">
            Builder pitch microsites, generated by Claude.
          </p>
        </div>
        <Link
          href="/admin/pitch-generator/new"
          className="inline-flex items-center gap-2 px-4 py-2.5 rounded-lg bg-c1 text-canvas font-medium hover:bg-c1/90 transition shadow-sm"
        >
          <Plus className="w-4 h-4" />
          New pitch
        </Link>
      </div>

      {/* Filters */}
      <form
        method="GET"
        className="glass-card p-4 border border-glass-border rounded-lg flex flex-col sm:flex-row gap-3 sm:items-center"
      >
        <div className="relative flex-1">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-fg-muted" />
          <input
            type="text"
            name="q"
            defaultValue={activeQuery}
            placeholder="Search by company name..."
            className="w-full pl-10 pr-3 py-2 rounded-md bg-canvas/60 border border-glass-border text-fg placeholder:text-fg-muted focus:outline-none focus:ring-2 focus:ring-c1/40"
          />
        </div>
        <select
          name="status"
          defaultValue={activeStatus === 'ALL' ? '' : activeStatus}
          className="px-3 py-2 rounded-md bg-canvas/60 border border-glass-border text-fg focus:outline-none focus:ring-2 focus:ring-c1/40"
        >
          <option value="">All statuses</option>
          {STATUS_VALUES.map((s) => (
            <option key={s} value={s}>
              {s}
            </option>
          ))}
        </select>
        <button
          type="submit"
          className="px-4 py-2 rounded-md bg-white/10 text-fg border border-glass-border hover:bg-white/15 transition"
        >
          Apply
        </button>
        {(activeQuery || activeStatus !== 'ALL') && (
          <Link
            href="/admin/pitch-generator"
            className="text-sm text-fg-muted hover:text-fg transition"
          >
            Clear
          </Link>
        )}
      </form>

      {/* Table or empty state */}
      {rows.length === 0 ? (
        <div className="glass-card p-12 border border-glass-border rounded-lg text-center space-y-4">
          <div className="inline-flex items-center justify-center w-12 h-12 rounded-full bg-c1/15 text-c1">
            <FileText className="w-6 h-6" />
          </div>
          <div>
            <h3 className="text-lg font-semibold text-fg">
              {activeQuery || activeStatus !== 'ALL'
                ? 'No pitches match these filters'
                : 'No pitches yet'}
            </h3>
            <p className="text-sm text-fg-muted mt-1">
              {activeQuery || activeStatus !== 'ALL'
                ? 'Try clearing the filters above.'
                : 'Generate a pitch to send to a builder prospect.'}
            </p>
          </div>
          <Link
            href="/admin/pitch-generator/new"
            className="inline-flex items-center gap-2 px-4 py-2.5 rounded-lg bg-c1 text-canvas font-medium hover:bg-c1/90 transition"
          >
            <Plus className="w-4 h-4" />
            New pitch
          </Link>
        </div>
      ) : (
        <div className="glass-card border border-glass-border rounded-lg overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead className="border-b border-glass-border bg-white/5">
                <tr className="text-fg-muted text-xs uppercase tracking-wide">
                  <th className="text-left py-3 px-4">Company</th>
                  <th className="text-left py-3 px-4">Style</th>
                  <th className="text-left py-3 px-4">Layout</th>
                  <th className="text-left py-3 px-4">Status</th>
                  <th className="text-right py-3 px-4">Cost</th>
                  <th className="text-left py-3 px-4 hidden md:table-cell">
                    By
                  </th>
                  <th className="text-left py-3 px-4 hidden lg:table-cell">
                    Created
                  </th>
                </tr>
              </thead>
              <tbody>
                {rows.map((r) => (
                  <tr
                    key={r.id}
                    className="border-b border-glass-border/40 hover:bg-white/5 transition"
                  >
                    <td className="py-3 px-4">
                      <Link
                        href={`/admin/pitch-generator/${r.id}`}
                        className="font-medium text-fg hover:text-c1 transition"
                      >
                        {r.companyName}
                      </Link>
                    </td>
                    <td className="py-3 px-4">
                      <span
                        className={`inline-flex px-2 py-0.5 text-xs font-medium rounded border ${styleBadgeClass(r.style)}`}
                      >
                        {r.style}
                      </span>
                    </td>
                    <td className="py-3 px-4 text-fg-muted">{r.layout}</td>
                    <td className="py-3 px-4">
                      <span
                        className={`inline-flex px-2 py-0.5 text-xs font-medium rounded border ${statusBadgeClass(r.status)}`}
                      >
                        {r.status}
                      </span>
                    </td>
                    <td className="py-3 px-4 text-right text-fg-muted font-mono text-xs">
                      {r.costEstimate != null
                        ? `$${r.costEstimate.toFixed(2)}`
                        : '—'}
                    </td>
                    <td className="py-3 px-4 text-fg-muted hidden md:table-cell">
                      {r.generatedByName || (r.generatedBy ? 'Auto' : 'System')}
                    </td>
                    <td className="py-3 px-4 text-fg-muted hidden lg:table-cell">
                      {formatDate(r.createdAt)}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {totalPages > 1 && (
            <div className="flex items-center justify-between px-4 py-3 border-t border-glass-border text-sm text-fg-muted">
              <div>
                Page {page} of {totalPages} · {total} pitches
              </div>
              <div className="flex gap-2">
                {page > 1 && (
                  <Link
                    href={{
                      pathname: '/admin/pitch-generator',
                      query: { ...params, page: String(page - 1) },
                    }}
                    className="px-3 py-1 rounded-md bg-white/10 hover:bg-white/15 transition"
                  >
                    Prev
                  </Link>
                )}
                {page < totalPages && (
                  <Link
                    href={{
                      pathname: '/admin/pitch-generator',
                      query: { ...params, page: String(page + 1) },
                    }}
                    className="px-3 py-1 rounded-md bg-white/10 hover:bg-white/15 transition"
                  >
                    Next
                  </Link>
                )}
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  )
}
