'use client'

import { useState, useEffect, useCallback } from 'react'

interface DemandForecast {
  category: string
  historical: { total6mo: number; avgMonthly: number; avgDaily: number; uniqueSkus: number }
  forecast: { next30days: number; next60days: number; next90days: number; seasonalFactor: number; confidence: number }
  pendingFromQuotes: number
  totalExpectedDemand30: number
}

interface ReorderRec {
  id: string; sku: string; productName: string; category: string
  quantityOnHand: number; reorderPoint: number; safetyStock: number
  avgDailyUsage: number; urgency: string; daysUntilStockout: number
  recommendedSupplier: any; aiReason: string; suggestedQty: number; estimatedCost: number
  allSuppliers: any[]
}

interface SuggestedPO {
  supplierId: string; supplierName: string; supplierType: string; leadTimeDays: number
  itemCount: number; totalCost: number; priority: string; suggestedOrderDate: string
  expectedDelivery: string; items: any[]; meetsMinOrder: boolean
}

interface SupplierScore {
  id: string; name: string; type: string; country: string
  compositeScore: number; grade: string
  scores: { quality: number; reliability: number; onTime: number; value: number }
  totalPOs: number; totalSpend: number; activeProducts: number
}

type Tab = 'overview' | 'demand' | 'reorder' | 'bestbuy' | 'schedule' | 'suppliers' | 'health'

export default function ProcurementIntelligencePage() {
  const [tab, setTab] = useState<Tab>('overview')
  const [loading, setLoading] = useState(false)
  const [setupDone, setSetupDone] = useState(false)
  const [forecasts, setForecasts] = useState<DemandForecast[]>([])
  const [demandInsights, setDemandInsights] = useState<string[]>([])
  const [topProducts, setTopProducts] = useState<any[]>([])
  const [recommendations, setRecommendations] = useState<ReorderRec[]>([])
  const [reorderSummary, setReorderSummary] = useState<any>(null)
  const [bestBuyAnalysis, setBestBuyAnalysis] = useState<any[]>([])
  const [bestBuyInsights, setBestBuyInsights] = useState<string[]>([])
  const [suggestedPOs, setSuggestedPOs] = useState<SuggestedPO[]>([])
  const [poSummary, setPoSummary] = useState<any>(null)
  const [poInsights, setPoInsights] = useState<string[]>([])
  const [scorecards, setScorecards] = useState<SupplierScore[]>([])
  const [healthData, setHealthData] = useState<any>(null)
  const [creatingPO, setCreatingPO] = useState<string | null>(null)

  useEffect(() => {
    fetch('/api/ops/procurement/setup', { method: 'POST' })
      .then(() => setSetupDone(true))
      .catch(() => setSetupDone(true))
  }, [])

  const runAnalysis = useCallback(async (action: string) => {
    setLoading(true)
    try {
      const res = await fetch('/api/ops/procurement/ai-assistant', {
        method: 'POST', headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ action }),
      })
      if (!res.ok) throw new Error('Analysis failed')
      return await res.json()
    } catch { return null } finally { setLoading(false) }
  }, [])

  const loadTab = useCallback(async (t: Tab) => {
    setTab(t)
    if (t === 'demand' || t === 'overview') {
      const d = await runAnalysis('demand_forecast')
      if (d) { setForecasts(d.forecasts || []); setDemandInsights(d.aiInsights || []); setTopProducts(d.topProducts || []) }
    }
    if (t === 'reorder' || t === 'overview') {
      const d = await runAnalysis('reorder_recommendations')
      if (d) { setRecommendations(d.recommendations || []); setReorderSummary(d.summary || null) }
    }
    if (t === 'bestbuy') {
      const d = await runAnalysis('best_buy_analysis')
      if (d) { setBestBuyAnalysis(d.analysis || []); setBestBuyInsights(d.aiInsights || []) }
    }
    if (t === 'schedule') {
      const d = await runAnalysis('po_schedule')
      if (d) { setSuggestedPOs(d.suggestedPOs || []); setPoSummary(d.summary || null); setPoInsights(d.aiInsights || []) }
    }
    if (t === 'suppliers') {
      const d = await runAnalysis('supplier_scorecard')
      if (d) setScorecards(d.scorecards || [])
    }
    if (t === 'health') {
      const d = await runAnalysis('inventory_health')
      if (d) setHealthData(d)
    }
  }, [runAnalysis])

  useEffect(() => { if (setupDone) loadTab('overview') }, [setupDone]) // eslint-disable-line

  const createPOFromSuggestion = async (po: SuggestedPO) => {
    setCreatingPO(po.supplierId)
    try {
      const res = await fetch('/api/ops/procurement/purchase-orders', {
        method: 'POST', headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          supplierId: po.supplierId, priority: po.priority, expectedDate: po.expectedDelivery,
          aiGenerated: true,
          aiReason: `Auto-generated by AI Procurement Brain. ${po.itemCount} items from ${po.supplierName}.`,
          items: po.items.map((i: any) => ({ productId: i.productId, sku: i.sku, productName: i.productName, quantity: i.suggestedQty, unitCost: i.unitCost })),
        }),
      })
      if (res.ok) { const d = await res.json(); alert(`PO ${d.poNumber} created! Review it in Purchase Orders.`) }
    } catch { alert('Failed to create PO') } finally { setCreatingPO(null) }
  }

  const TABS: { id: Tab; label: string; icon: string }[] = [
    { id: 'overview', label: 'AI Overview', icon: '🤖' }, { id: 'demand', label: 'Demand Forecast', icon: '📈' },
    { id: 'reorder', label: 'Reorder Alerts', icon: '⚠️' }, { id: 'bestbuy', label: 'Best Buy Analysis', icon: '💰' },
    { id: 'schedule', label: 'PO Scheduler', icon: '📅' }, { id: 'suppliers', label: 'Supplier Scorecard', icon: '🏢' },
    { id: 'health', label: 'Inventory Health', icon: '❤️' },
  ]

  const urgencyColor = (u: string) => u === 'CRITICAL' ? '#DC2626' : u === 'URGENT' ? '#EA580C' : u === 'REORDER_NOW' ? '#D97706' : u === 'REORDER_SOON' ? '#2563EB' : '#16A34A'
  const gradeColor = (g: string) => g === 'A' ? '#16A34A' : g === 'B' ? '#2563EB' : g === 'C' ? '#D97706' : g === 'D' ? '#EA580C' : '#DC2626'

  return (
    <div>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 24 }}>
        <div>
          <h1 style={{ fontSize: 24, fontWeight: 700, color: '#1B4F72', margin: 0 }}>🤖 AI Procurement Brain</h1>
          <p style={{ color: '#6B7280', fontSize: 14, marginTop: 4 }}>Intelligent purchasing, demand forecasting & inventory optimization</p>
        </div>
        <button onClick={() => loadTab(tab)} disabled={loading}
          style={{ padding: '8px 20px', borderRadius: 8, border: 'none', cursor: 'pointer', background: loading ? '#9CA3AF' : '#E67E22', color: '#fff', fontWeight: 600, fontSize: 14 }}>
          {loading ? '⏳ Analyzing...' : '🔄 Refresh'}
        </button>
      </div>

      <div style={{ display: 'flex', gap: 4, marginBottom: 24, flexWrap: 'wrap', borderBottom: '2px solid #E5E7EB', paddingBottom: 2 }}>
        {TABS.map(t => (
          <button key={t.id} onClick={() => loadTab(t.id)}
            style={{ padding: '10px 16px', border: 'none', borderBottom: tab === t.id ? '3px solid #1B4F72' : '3px solid transparent',
              background: tab === t.id ? '#EBF5FB' : 'transparent', color: tab === t.id ? '#1B4F72' : '#6B7280',
              fontWeight: tab === t.id ? 700 : 500, fontSize: 13, cursor: 'pointer', borderRadius: '8px 8px 0 0' }}>
            {t.icon} {t.label}
          </button>
        ))}
      </div>

      {loading && (
        <div style={{ textAlign: 'center', padding: 60, color: '#6B7280' }}>
          <div style={{ fontSize: 48, marginBottom: 16 }}>🧠</div>
          <p style={{ fontSize: 18, fontWeight: 600 }}>AI is analyzing your procurement data...</p>
          <p style={{ fontSize: 14 }}>Running demand forecasts, supplier comparisons & inventory checks</p>
        </div>
      )}

      {/* ── OVERVIEW TAB ─────────────────────────────────────────────── */}
      {!loading && tab === 'overview' && (
        <div>
          <div style={{ background: 'linear-gradient(135deg, #1B4F72, #2980B9)', borderRadius: 12, padding: 24, marginBottom: 24, color: '#fff' }}>
            <h2 style={{ margin: '0 0 16px', fontSize: 18, fontWeight: 700 }}>🧠 AI Procurement Insights</h2>
            {demandInsights.map((ins, i) => <p key={i} style={{ margin: '8px 0', fontSize: 14, lineHeight: 1.6, opacity: 0.95 }}>{ins}</p>)}
          </div>

          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: 16, marginBottom: 24 }}>
            <Card label="Items Need Reorder" value={reorderSummary?.totalItemsNeedReorder || 0} color="#DC2626" icon="⚠️" />
            <Card label="Critical Items" value={reorderSummary?.criticalCount || 0} color="#EA580C" icon="🚨" />
            <Card label="Est. Reorder Cost" value={`$${(reorderSummary?.estimatedTotalCost || 0).toLocaleString('en-US', { minimumFractionDigits: 0 })}`} color="#1B4F72" icon="💰" />
            <Card label="Categories Tracked" value={forecasts.length} color="#16A34A" icon="📊" />
          </div>

          {forecasts.length > 0 && (
            <div style={{ background: '#fff', borderRadius: 12, border: '1px solid #E5E7EB', padding: 20, marginBottom: 24 }}>
              <h3 style={{ margin: '0 0 16px', color: '#1B4F72', fontSize: 16, fontWeight: 700 }}>📈 30-Day Demand Forecast by Category</h3>
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))', gap: 12 }}>
                {forecasts.map((f, i) => (
                  <div key={i} style={{ background: '#F8FAFC', borderRadius: 8, padding: 16, border: '1px solid #E2E8F0' }}>
                    <div style={{ fontWeight: 700, fontSize: 14, color: '#1B4F72', marginBottom: 8 }}>{f.category}</div>
                    <div style={{ fontSize: 28, fontWeight: 800, color: '#E67E22' }}>{f.forecast.next30days}</div>
                    <div style={{ fontSize: 11, color: '#6B7280' }}>units forecasted</div>
                    <div style={{ marginTop: 8, fontSize: 12, color: '#6B7280' }}>Avg: {f.historical.avgMonthly}/mo • Pending: {f.pendingFromQuotes}</div>
                    <div style={{ marginTop: 4, fontSize: 11, color: f.forecast.seasonalFactor > 1 ? '#16A34A' : '#DC2626' }}>
                      Season: {f.forecast.seasonalFactor > 1 ? '↑' : '↓'} {Math.round(Math.abs(f.forecast.seasonalFactor - 1) * 100)}%
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {recommendations.length > 0 && (
            <div style={{ background: '#fff', borderRadius: 12, border: '1px solid #E5E7EB', padding: 20 }}>
              <h3 style={{ margin: '0 0 16px', color: '#1B4F72', fontSize: 16 }}>⚠️ Top Reorder Alerts ({recommendations.length})</h3>
              {recommendations.slice(0, 8).map((r, i) => (
                <div key={i} style={{ display: 'flex', alignItems: 'center', gap: 12, padding: '10px 0', borderBottom: '1px solid #F3F4F6' }}>
                  <span style={{ padding: '4px 10px', borderRadius: 6, fontSize: 11, fontWeight: 700, color: '#fff', background: urgencyColor(r.urgency) }}>{r.urgency}</span>
                  <div style={{ flex: 1 }}>
                    <div style={{ fontWeight: 600, fontSize: 14 }}>{r.productName}</div>
                    <div style={{ fontSize: 12, color: '#6B7280' }}>{r.sku} • {r.quantityOnHand} on hand • {r.daysUntilStockout} days left</div>
                  </div>
                  <div style={{ textAlign: 'right', fontSize: 12 }}>
                    <div style={{ fontWeight: 600, color: '#1B4F72' }}>Order {r.suggestedQty} units</div>
                    <div style={{ color: '#6B7280' }}>${r.estimatedCost.toLocaleString('en-US', { minimumFractionDigits: 2 })}</div>
                  </div>
                </div>
              ))}
              {recommendations.length > 8 && (
                <button onClick={() => loadTab('reorder')} style={{ marginTop: 12, background: 'none', border: 'none', color: '#2563EB', cursor: 'pointer', fontSize: 13, fontWeight: 600 }}>
                  View all {recommendations.length} alerts →
                </button>
              )}
            </div>
          )}

          {forecasts.length === 0 && recommendations.length === 0 && !loading && (
            <div style={{ textAlign: 'center', padding: 60, color: '#6B7280', background: '#F9FAFB', borderRadius: 12 }}>
              <div style={{ fontSize: 48, marginBottom: 16 }}>📦</div>
              <h3 style={{ color: '#1B4F72', marginBottom: 8 }}>Getting Started</h3>
              <p>Add suppliers and sync your product catalog to start receiving AI procurement recommendations.</p>
              <div style={{ display: 'flex', gap: 12, justifyContent: 'center', marginTop: 20 }}>
                <a href="/ops/vendors" style={{ padding: '10px 20px', background: '#1B4F72', color: '#fff', borderRadius: 8, textDecoration: 'none', fontWeight: 600, fontSize: 14 }}>Add Suppliers →</a>
                <button onClick={async () => {
                  const res = await fetch('/api/ops/procurement/inventory', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'sync_products' }) })
                  if (res.ok) { const d = await res.json(); alert(d.message); loadTab('overview') }
                }} style={{ padding: '10px 20px', background: '#E67E22', color: '#fff', borderRadius: 8, border: 'none', cursor: 'pointer', fontWeight: 600, fontSize: 14 }}>
                  Sync Products to Inventory →
                </button>
              </div>
            </div>
          )}
        </div>
      )}

      {/* ── DEMAND FORECAST TAB ──────────────────────────────────────── */}
      {!loading && tab === 'demand' && (
        <div>
          <div style={{ background: '#FFF7ED', borderRadius: 12, padding: 20, marginBottom: 24, border: '1px solid #FED7AA' }}>
            <h3 style={{ margin: '0 0 12px', color: '#9A3412', fontSize: 16 }}>🧠 AI Demand Analysis</h3>
            {demandInsights.map((ins, i) => <p key={i} style={{ margin: '6px 0', fontSize: 13, color: '#78350F', lineHeight: 1.5 }}>{ins}</p>)}
          </div>
          {forecasts.map((f, i) => (
            <div key={i} style={{ background: '#fff', borderRadius: 12, border: '1px solid #E5E7EB', padding: 20, marginBottom: 16 }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 }}>
                <h3 style={{ margin: 0, color: '#1B4F72', fontSize: 16 }}>{f.category}</h3>
                <span style={{ fontSize: 12, color: '#6B7280', background: '#F3F4F6', padding: '4px 10px', borderRadius: 20 }}>{f.historical.uniqueSkus} SKUs</span>
              </div>
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(130px, 1fr))', gap: 10 }}>
                <Stat label="6-Mo Total" value={f.historical.total6mo} />
                <Stat label="Monthly Avg" value={f.historical.avgMonthly} />
                <Stat label="Daily Avg" value={f.historical.avgDaily} />
                <Stat label="Next 30 Days" value={f.forecast.next30days} hl />
                <Stat label="Next 60 Days" value={f.forecast.next60days} />
                <Stat label="Next 90 Days" value={f.forecast.next90days} />
                <Stat label="Pending Quotes" value={f.pendingFromQuotes} />
                <Stat label="Expected Demand" value={f.totalExpectedDemand30} hl />
              </div>
            </div>
          ))}
          {topProducts.length > 0 && (
            <div style={{ background: '#fff', borderRadius: 12, border: '1px solid #E5E7EB', padding: 20 }}>
              <h3 style={{ margin: '0 0 16px', color: '#1B4F72', fontSize: 16 }}>🏆 Top 20 Products by Demand</h3>
              <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 13 }}>
                <thead><tr style={{ background: '#F8FAFC' }}>
                  {['#', 'Product', 'SKU', 'Category', '6-Mo Total', 'Avg/Mo'].map(h => (
                    <th key={h} style={{ textAlign: h === '#' || h === 'Product' || h === 'SKU' || h === 'Category' ? 'left' : 'right', padding: '8px 10px', color: '#6B7280', fontWeight: 600 }}>{h}</th>
                  ))}
                </tr></thead>
                <tbody>
                  {topProducts.map((p: any, i: number) => (
                    <tr key={i} style={{ borderBottom: '1px solid #F3F4F6' }}>
                      <td style={{ padding: '8px 10px', fontWeight: 700, color: i < 3 ? '#E67E22' : '#6B7280' }}>{i + 1}</td>
                      <td style={{ padding: '8px 10px', fontWeight: 500 }}>{p.name}</td>
                      <td style={{ padding: '8px 10px', color: '#6B7280', fontFamily: 'monospace', fontSize: 12 }}>{p.sku}</td>
                      <td style={{ padding: '8px 10px' }}>{p.category}</td>
                      <td style={{ padding: '8px 10px', textAlign: 'right', fontWeight: 600 }}>{p.totalOrdered}</td>
                      <td style={{ padding: '8px 10px', textAlign: 'right' }}>{p.avgMonthly}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>
      )}

      {/* ── REORDER ALERTS TAB ──────────────────────────────────────── */}
      {!loading && tab === 'reorder' && (
        <div>
          {reorderSummary && (
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))', gap: 16, marginBottom: 24 }}>
              <Card label="Need Reorder" value={reorderSummary.totalItemsNeedReorder} color="#D97706" icon="📦" />
              <Card label="Critical" value={reorderSummary.criticalCount} color="#DC2626" icon="🚨" />
              <Card label="Urgent" value={reorderSummary.urgentCount} color="#EA580C" icon="⚠️" />
              <Card label="Est. Cost" value={`$${reorderSummary.estimatedTotalCost.toLocaleString('en-US', { minimumFractionDigits: 0, maximumFractionDigits: 0 })}`} color="#1B4F72" icon="💰" />
            </div>
          )}
          {recommendations.map((r, i) => (
            <div key={i} style={{ background: '#fff', borderRadius: 12, border: `2px solid ${urgencyColor(r.urgency)}20`, borderLeft: `4px solid ${urgencyColor(r.urgency)}`, padding: 20, marginBottom: 12 }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 12 }}>
                <div>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 4 }}>
                    <span style={{ padding: '3px 8px', borderRadius: 4, fontSize: 11, fontWeight: 700, color: '#fff', background: urgencyColor(r.urgency) }}>{r.urgency}</span>
                    <span style={{ fontWeight: 700, fontSize: 16 }}>{r.productName}</span>
                  </div>
                  <div style={{ fontSize: 12, color: '#6B7280' }}>{r.sku} • {r.category} • {r.daysUntilStockout} days until stockout</div>
                </div>
                <div style={{ textAlign: 'right', fontSize: 12, color: '#6B7280' }}>
                  <div>On Hand: <strong>{r.quantityOnHand}</strong></div>
                  <div>Reorder Pt: {r.reorderPoint}</div>
                </div>
              </div>
              <div style={{ background: '#F0F9FF', borderRadius: 8, padding: 12, marginBottom: 12 }}>
                <div style={{ fontSize: 12, fontWeight: 700, color: '#1B4F72', marginBottom: 4 }}>🤖 AI Recommendation</div>
                <p style={{ margin: 0, fontSize: 13, color: '#334155', lineHeight: 1.5 }}>{r.aiReason}</p>
              </div>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', fontSize: 13 }}>
                <div>
                  <strong>Order:</strong> {r.suggestedQty} units
                  {r.recommendedSupplier && <span> from <strong>{r.recommendedSupplier.supplierName}</strong> ({r.recommendedSupplier.supplierType})</span>}
                  <span style={{ color: '#6B7280' }}> • Est. ${r.estimatedCost.toLocaleString('en-US', { minimumFractionDigits: 2 })}</span>
                </div>
                {r.allSuppliers.length > 1 && <span style={{ fontSize: 11, color: '#2563EB' }}>{r.allSuppliers.length} suppliers</span>}
              </div>
            </div>
          ))}
          {recommendations.length === 0 && (
            <div style={{ textAlign: 'center', padding: 60, color: '#16A34A', background: '#F0FDF4', borderRadius: 12 }}>
              <div style={{ fontSize: 48 }}>✅</div><h3>All stock levels healthy</h3>
              <p style={{ color: '#6B7280' }}>No items currently need reordering.</p>
            </div>
          )}
        </div>
      )}

      {/* ── BEST BUY TAB ────────────────────────────────────────────── */}
      {!loading && tab === 'bestbuy' && (
        <div>
          <div style={{ background: '#F0FDF4', borderRadius: 12, padding: 20, marginBottom: 24, border: '1px solid #BBF7D0' }}>
            <h3 style={{ margin: '0 0 12px', color: '#166534', fontSize: 16 }}>💰 Best Buy Insights</h3>
            {bestBuyInsights.map((ins, i) => <p key={i} style={{ margin: '6px 0', fontSize: 13, color: '#14532D', lineHeight: 1.5 }}>{ins}</p>)}
          </div>
          {bestBuyAnalysis.map((cat, ci) => (
            <div key={ci} style={{ background: '#fff', borderRadius: 12, border: '1px solid #E5E7EB', padding: 20, marginBottom: 16 }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 }}>
                <h3 style={{ margin: 0, color: '#1B4F72', fontSize: 16 }}>{cat.category}</h3>
                {cat.avgOverseasSavings > 0 && <span style={{ background: '#DCFCE7', color: '#166534', padding: '4px 12px', borderRadius: 20, fontSize: 12, fontWeight: 600 }}>Avg {cat.avgOverseasSavings}% overseas savings</span>}
              </div>
              {cat.products.map((p: any, pi: number) => (
                <div key={pi} style={{ padding: '10px 0', borderBottom: '1px solid #F3F4F6', display: 'flex', alignItems: 'center', gap: 12 }}>
                  <div style={{ flex: 1 }}>
                    <div style={{ fontWeight: 600, fontSize: 14 }}>{p.productName}</div>
                    <div style={{ fontSize: 12, color: '#6B7280' }}>{p.supplierCount} suppliers</div>
                  </div>
                  {p.domesticBest && (
                    <div style={{ textAlign: 'center', padding: '4px 12px', background: '#EFF6FF', borderRadius: 8 }}>
                      <div style={{ fontSize: 11, color: '#1E40AF' }}>Domestic</div>
                      <div style={{ fontWeight: 700, fontSize: 14 }}>${Number(p.domesticBest.landedCost).toFixed(2)}</div>
                      <div style={{ fontSize: 10, color: '#6B7280' }}>{p.domesticBest.supplierName}</div>
                    </div>
                  )}
                  {p.overseasBest && (
                    <div style={{ textAlign: 'center', padding: '4px 12px', background: '#F0FDF4', borderRadius: 8 }}>
                      <div style={{ fontSize: 11, color: '#166534' }}>Overseas</div>
                      <div style={{ fontWeight: 700, fontSize: 14 }}>${Number(p.overseasBest.landedCost).toFixed(2)}</div>
                      <div style={{ fontSize: 10, color: '#6B7280' }}>{p.overseasBest.supplierName}</div>
                    </div>
                  )}
                  {p.overseasSavingsPct > 0 && (
                    <div style={{ background: '#DCFCE7', color: '#166534', padding: '6px 12px', borderRadius: 8, fontWeight: 700, fontSize: 14, minWidth: 60, textAlign: 'center' }}>-{p.overseasSavingsPct}%</div>
                  )}
                </div>
              ))}
            </div>
          ))}
          {bestBuyAnalysis.length === 0 && (
            <div style={{ textAlign: 'center', padding: 60, color: '#6B7280', background: '#F9FAFB', borderRadius: 12 }}>
              <div style={{ fontSize: 48 }}>🏪</div><h3>No supplier product data yet</h3>
              <p>Add suppliers and their product pricing to see best-buy comparisons.</p>
            </div>
          )}
        </div>
      )}

      {/* ── PO SCHEDULER TAB ────────────────────────────────────────── */}
      {!loading && tab === 'schedule' && (
        <div>
          {poSummary && (
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))', gap: 16, marginBottom: 24 }}>
              <Card label="Suggested POs" value={poSummary.totalPOs} color="#1B4F72" icon="📋" />
              <Card label="Urgent POs" value={poSummary.urgentPOs} color="#DC2626" icon="🚨" />
              <Card label="Total Items" value={poSummary.totalItems} color="#E67E22" icon="📦" />
              <Card label="Est. Spend" value={`$${poSummary.totalValue.toLocaleString('en-US', { minimumFractionDigits: 0, maximumFractionDigits: 0 })}`} color="#16A34A" icon="💰" />
            </div>
          )}
          <div style={{ background: '#FFF7ED', borderRadius: 12, padding: 16, marginBottom: 24, border: '1px solid #FED7AA' }}>
            {poInsights.map((ins, i) => <p key={i} style={{ margin: '4px 0', fontSize: 13, color: '#78350F' }}>{ins}</p>)}
          </div>
          {suggestedPOs.map((po, i) => (
            <div key={i} style={{ background: '#fff', borderRadius: 12, border: '1px solid #E5E7EB', borderLeft: `4px solid ${po.priority === 'URGENT' ? '#DC2626' : po.priority === 'HIGH' ? '#EA580C' : '#2563EB'}`, padding: 20, marginBottom: 16 }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 12 }}>
                <div>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                    <span style={{ padding: '3px 8px', borderRadius: 4, fontSize: 11, fontWeight: 700, color: '#fff', background: po.priority === 'URGENT' ? '#DC2626' : po.priority === 'HIGH' ? '#EA580C' : '#2563EB' }}>{po.priority}</span>
                    <h3 style={{ margin: 0, fontSize: 16 }}>{po.supplierName}</h3>
                    <span style={{ fontSize: 11, color: '#6B7280', background: '#F3F4F6', padding: '2px 8px', borderRadius: 12 }}>{po.supplierType}</span>
                  </div>
                  <div style={{ fontSize: 12, color: '#6B7280', marginTop: 4 }}>{po.itemCount} items • Lead: {po.leadTimeDays}d • ETA: {po.expectedDelivery}</div>
                </div>
                <div style={{ textAlign: 'right' }}>
                  <div style={{ fontSize: 20, fontWeight: 800, color: '#1B4F72' }}>${po.totalCost.toLocaleString('en-US', { minimumFractionDigits: 2 })}</div>
                  {!po.meetsMinOrder && <div style={{ fontSize: 11, color: '#DC2626' }}>⚠️ Below min order</div>}
                </div>
              </div>
              <div style={{ background: '#F8FAFC', borderRadius: 8, padding: 12, marginBottom: 12 }}>
                {po.items.slice(0, 5).map((item: any, j: number) => (
                  <div key={j} style={{ display: 'flex', justifyContent: 'space-between', padding: '4px 0', fontSize: 13 }}>
                    <span>{item.productName} ({item.sku})</span>
                    <span style={{ color: '#6B7280' }}>{item.suggestedQty} × ${Number(item.unitCost).toFixed(2)}</span>
                  </div>
                ))}
                {po.items.length > 5 && <div style={{ fontSize: 12, color: '#6B7280', marginTop: 4 }}>...and {po.items.length - 5} more</div>}
              </div>
              <button onClick={() => createPOFromSuggestion(po)} disabled={creatingPO === po.supplierId}
                style={{ padding: '8px 20px', borderRadius: 8, border: 'none', cursor: 'pointer', background: creatingPO === po.supplierId ? '#9CA3AF' : '#1B4F72', color: '#fff', fontWeight: 600, fontSize: 13 }}>
                {creatingPO === po.supplierId ? '⏳ Creating...' : '📋 Generate Draft PO'}
              </button>
            </div>
          ))}
          {suggestedPOs.length === 0 && (
            <div style={{ textAlign: 'center', padding: 60, color: '#16A34A', background: '#F0FDF4', borderRadius: 12 }}>
              <div style={{ fontSize: 48 }}>✅</div><h3>No POs needed</h3><p style={{ color: '#6B7280' }}>All inventory above reorder points.</p>
            </div>
          )}
        </div>
      )}

      {/* ── SUPPLIER SCORECARD TAB ──────────────────────────────────── */}
      {!loading && tab === 'suppliers' && (
        <div>
          {scorecards.map((s, i) => (
            <div key={i} style={{ background: '#fff', borderRadius: 12, border: '1px solid #E5E7EB', padding: 20, marginBottom: 16 }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 }}>
                <div>
                  <h3 style={{ margin: 0, fontSize: 16 }}>{s.name}</h3>
                  <div style={{ fontSize: 12, color: '#6B7280', marginTop: 2 }}>{s.type} • {s.country} • {s.activeProducts} products • {s.totalPOs} POs</div>
                </div>
                <div style={{ textAlign: 'center' }}>
                  <div style={{ width: 48, height: 48, borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center', background: gradeColor(s.grade) + '20', color: gradeColor(s.grade), fontWeight: 800, fontSize: 20 }}>{s.grade}</div>
                  <div style={{ fontSize: 10, color: '#6B7280', marginTop: 2 }}>{s.compositeScore}/100</div>
                </div>
              </div>
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 8 }}>
                {(['quality', 'reliability', 'onTime', 'value'] as const).map(k => (
                  <div key={k}>
                    <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 11, color: '#6B7280', marginBottom: 4 }}>
                      <span>{k.charAt(0).toUpperCase() + k.slice(1)}</span><span style={{ fontWeight: 600 }}>{s.scores[k]}%</span>
                    </div>
                    <div style={{ background: '#F3F4F6', borderRadius: 4, height: 8, overflow: 'hidden' }}>
                      <div style={{ width: `${s.scores[k]}%`, height: '100%', background: s.scores[k] >= 80 ? '#16A34A' : s.scores[k] >= 60 ? '#D97706' : '#DC2626', borderRadius: 4 }} />
                    </div>
                  </div>
                ))}
              </div>
            </div>
          ))}
          {scorecards.length === 0 && (
            <div style={{ textAlign: 'center', padding: 60, color: '#6B7280', background: '#F9FAFB', borderRadius: 12 }}>
              <div style={{ fontSize: 48 }}>🏢</div><h3>No suppliers yet</h3><p>Add suppliers to see AI-powered scorecards.</p>
              <a href="/ops/vendors" style={{ display: 'inline-block', padding: '10px 20px', background: '#1B4F72', color: '#fff', borderRadius: 8, textDecoration: 'none', fontWeight: 600, marginTop: 12 }}>Add Suppliers →</a>
            </div>
          )}
        </div>
      )}

      {/* ── INVENTORY HEALTH TAB ────────────────────────────────────── */}
      {!loading && tab === 'health' && healthData && (
        <div>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: 16, marginBottom: 24 }}>
            <Card label="Health Score" value={`${healthData.healthScore}/100`} color={healthData.healthScore >= 80 ? '#16A34A' : healthData.healthScore >= 60 ? '#D97706' : '#DC2626'} icon="❤️" />
            <Card label="Total SKUs" value={healthData.totals?.totalSkus || 0} color="#1B4F72" icon="📦" />
            <Card label="Inventory Value" value={`$${Number(healthData.totals?.totalInventoryValue || 0).toLocaleString('en-US', { minimumFractionDigits: 0, maximumFractionDigits: 0 })}`} color="#16A34A" icon="💰" />
            <Card label="Avg Days Supply" value={healthData.totals?.avgDaysOfSupply || '--'} color="#2563EB" icon="📅" />
          </div>
          {healthData.byCategory?.length > 0 && (
            <div style={{ background: '#fff', borderRadius: 12, border: '1px solid #E5E7EB', padding: 20 }}>
              <h3 style={{ margin: '0 0 16px', color: '#1B4F72', fontSize: 16 }}>Health by Category</h3>
              <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 13 }}>
                <thead><tr style={{ background: '#F8FAFC' }}>
                  {['Category', 'Items', 'Units', 'Value', 'OOS', 'Critical', 'Low', 'Over', 'Days Supply'].map(h => (
                    <th key={h} style={{ textAlign: h === 'Category' ? 'left' : 'right', padding: '8px 10px', color: '#6B7280', fontWeight: 600 }}>{h}</th>
                  ))}
                </tr></thead>
                <tbody>
                  {healthData.byCategory.map((c: any, i: number) => (
                    <tr key={i} style={{ borderBottom: '1px solid #F3F4F6' }}>
                      <td style={{ padding: '8px 10px', fontWeight: 600 }}>{c.category}</td>
                      <td style={{ padding: '8px 10px', textAlign: 'right' }}>{c.totalItems}</td>
                      <td style={{ padding: '8px 10px', textAlign: 'right' }}>{c.totalUnits?.toLocaleString()}</td>
                      <td style={{ padding: '8px 10px', textAlign: 'right' }}>${Number(c.totalValue).toLocaleString()}</td>
                      <td style={{ padding: '8px 10px', textAlign: 'right', color: c.outOfStock > 0 ? '#DC2626' : '#16A34A', fontWeight: c.outOfStock > 0 ? 700 : 400 }}>{c.outOfStock}</td>
                      <td style={{ padding: '8px 10px', textAlign: 'right', color: c.critical > 0 ? '#EA580C' : '#16A34A' }}>{c.critical}</td>
                      <td style={{ padding: '8px 10px', textAlign: 'right', color: c.lowStock > 0 ? '#D97706' : '#16A34A' }}>{c.lowStock}</td>
                      <td style={{ padding: '8px 10px', textAlign: 'right', color: c.overstock > 0 ? '#7C3AED' : '#16A34A' }}>{c.overstock}</td>
                      <td style={{ padding: '8px 10px', textAlign: 'right' }}>{c.avgDaysOfSupply || '--'}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>
      )}
    </div>
  )
}

function Card({ label, value, color, icon }: { label: string; value: string | number; color: string; icon: string }) {
  return (
    <div style={{ background: '#fff', borderRadius: 12, border: '1px solid #E5E7EB', padding: 16 }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <span style={{ fontSize: 12, color: '#6B7280' }}>{label}</span><span style={{ fontSize: 20 }}>{icon}</span>
      </div>
      <div style={{ fontSize: 28, fontWeight: 800, color, marginTop: 4 }}>{value}</div>
    </div>
  )
}

function Stat({ label, value, hl }: { label: string; value: number; hl?: boolean }) {
  return (
    <div style={{ background: hl ? '#FFF7ED' : '#F8FAFC', borderRadius: 8, padding: 12, textAlign: 'center', border: hl ? '1px solid #FED7AA' : '1px solid #E2E8F0' }}>
      <div style={{ fontSize: 11, color: '#6B7280', marginBottom: 4 }}>{label}</div>
      <div style={{ fontSize: 20, fontWeight: 700, color: hl ? '#E67E22' : '#1B4F72' }}>{value}</div>
    </div>
  )
}
