'use client'

import { useState, useEffect } from 'react'
import { useRouter } from 'next/navigation'
import { CalendarDays } from 'lucide-react'
import { EmptyState, PageHeader } from '@/components/ui'
import { CreateScheduleModal } from '../components/CreateScheduleModal'
import { ScheduleEntryModal } from '../components/ScheduleEntryModal'

const DAYS = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat']
const HOURS = ['6 AM', '7 AM', '8 AM', '9 AM', '10 AM', '11 AM', '12 PM', '1 PM', '2 PM', '3 PM', '4 PM', '5 PM']

const ENTRY_TYPE_COLORS: Record<string, string> = {
  DELIVERY: '#3B82F6',
  INSTALLATION: '#10B981',
  PICKUP: '#FBBF24',
  RETURN: '#F97316',
  INSPECTION: '#A78BFA',
  RESTOCKING: '#9CA3AF',
}

const STATUS_CONFIG: Record<string, { border: string; icon: string }> = {
  TENTATIVE: { border: 'border-dashed', icon: '' },
  FIRM: { border: 'border-solid', icon: '' },
  IN_PROGRESS: { border: 'border-solid', icon: '▶' },
  COMPLETED: { border: 'border-solid', icon: '✓' },
  RESCHEDULED: { border: 'border-solid line-through', icon: '' },
  CANCELLED: { border: 'border-solid line-through text-red-600', icon: '✕' },
}

interface ScheduleEntry {
  id: string
  jobId?: string
  entryType: string
  title: string
  scheduledDate: string
  scheduledTime: string
  status: string
  notes: string
  isAutoGenerated?: boolean
  job: {
    builderName: string
    jobAddress: string
    community: string
    lotBlock: string
    status: string
  }
  crew: {
    name: string
    crewType?: string
  }
}

interface Crew {
  name: string
  crewType?: string
}

export default function SchedulePage() {
  const router = useRouter()
  const [view, setView] = useState<'week' | 'day' | 'list'>('week')
  const [entries, setEntries] = useState<ScheduleEntry[]>([])
  const [crews, setCrews] = useState<Crew[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [weekOffset, setWeekOffset] = useState(0)
  const [isCreateModalOpen, setIsCreateModalOpen] = useState(false)
  const [selectedEntryId, setSelectedEntryId] = useState<string | null>(null)

  // Handle clicking a schedule entry — auto-generated job entries navigate to job detail
  const handleEntryClick = (entry: any) => {
    if (entry.id?.startsWith('job-')) {
      router.push(`/ops/jobs/${entry.jobId}`)
    } else {
      setSelectedEntryId(entry.id)
    }
  }

  // Get current week dates
  const today = new Date()
  const monday = new Date(today)
  monday.setDate(today.getDate() - ((today.getDay() + 6) % 7))

  // Apply week offset
  const displayMonday = new Date(monday)
  displayMonday.setDate(monday.getDate() + weekOffset * 7)

  const weekDates = DAYS.map((day, i) => {
    const date = new Date(displayMonday)
    date.setDate(displayMonday.getDate() + i)
    return {
      day,
      date: date.getDate(),
      month: date.toLocaleDateString('en-US', { month: 'short' }),
      fullDate: date,
      isToday: date.toDateString() === today.toDateString(),
    }
  })

  // Fetch data from API
  const fetchData = async () => {
    try {
      setLoading(true)
      const startDate = weekDates[0].fullDate.toISOString().split('T')[0]
      const endDate = weekDates[5].fullDate.toISOString().split('T')[0]

      const response = await fetch(
        `/api/ops/schedule?startDate=${startDate}&endDate=${endDate}`
      )

      if (!response.ok) {
        throw new Error(`API error: ${response.statusText}`)
      }

      const data = await response.json()
      const loadedEntries = data.data || data.entries || []
      setEntries(loadedEntries)

      // Extract unique crews from entries
      const uniqueCrews = Array.from(
        new Map(
          loadedEntries
            .filter((e: ScheduleEntry) => e.crew)
            .map((e: ScheduleEntry) => [e.crew.name, e.crew])
        ).values()
      ) as Crew[]
      setCrews(uniqueCrews)
      setError(null)
    } catch (err) {
      console.error('Failed to fetch schedule:', err)
      setError(err instanceof Error ? err.message : 'Failed to load schedule')
      setEntries([])
      setCrews([])
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    fetchData()
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [weekOffset])

  // Helper: extract YYYY-MM-DD from an ISO date string (avoids timezone shift)
  const toDateKey = (isoStr: string) => isoStr?.substring(0, 10) || ''
  const dateToKey = (d: Date) =>
    `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`

  // Calculate crew summaries
  const crewSummaries = crews.map((crew) => {
    const crewEntries = entries.filter((e) => e.crew?.name === crew.name)
    return {
      ...crew,
      count: crewEntries.length,
    }
  })

  // Calculate today stats
  const todayKey = dateToKey(today)
  const todayEntries = entries.filter((e) => toDateKey(e.scheduledDate) === todayKey)
  const todayDeliveries = todayEntries.filter((e) => e.entryType === 'DELIVERY').length
  const todayInstalls = todayEntries.filter((e) => e.entryType === 'INSTALLATION').length

  // Calculate week stats
  const weekDeliveries = entries.filter((e) => e.entryType === 'DELIVERY').length
  const weekInstalls = entries.filter((e) => e.entryType === 'INSTALLATION').length

  // Get entries for a specific date and hour
  // Entries without a scheduledTime default to 7 AM (standard crew start)
  const getEntriesForSlot = (date: Date, hour: number) => {
    const slotKey = dateToKey(date)
    return entries.filter((e) => {
      const entryTime = e.scheduledTime ? parseInt(e.scheduledTime.split(':')[0]) : 7
      return toDateKey(e.scheduledDate) === slotKey && entryTime === hour
    })
  }

  const handlePrevWeek = () => setWeekOffset((w) => w - 1)
  const handleNextWeek = () => setWeekOffset((w) => w + 1)

  if (loading) {
    return (
      <div className="space-y-6">
        <PageHeader
          title="Schedule & Dispatch"
          description="Loading schedule..."
        />
        <div className="bg-white rounded-xl border p-8 text-center text-gray-400">
          <p className="text-lg">Loading schedule data...</p>
        </div>
      </div>
    )
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <PageHeader
        title="Schedule & Dispatch"
        description="Delivery routes, install crews, and pickup scheduling"
        actions={
          <div className="flex gap-2">
            <button
              onClick={() => setIsCreateModalOpen(true)}
              className="px-3 py-1.5 text-sm bg-data-positive text-white rounded-lg hover:bg-data-positive/90"
            >
              + Schedule Delivery
            </button>
            <button
              onClick={() => setIsCreateModalOpen(true)}
              className="px-3 py-1.5 text-sm bg-signal text-fg-on-accent rounded-lg hover:bg-signal-hover"
            >
              + Schedule Install
            </button>
          </div>
        }
      />

      {/* View toggle & navigation */}
      <div className="bg-white rounded-xl border p-4 flex items-center justify-between">
        <div className="flex items-center gap-4">
          <button
            onClick={handlePrevWeek}
            className="px-2 py-1 text-gray-400 hover:text-gray-600 hover:bg-gray-100 rounded font-semibold transition"
          >
            ←
          </button>
          {weekOffset !== 0 && (
            <button
              onClick={() => setWeekOffset(0)}
              className="px-2 py-1 text-xs font-semibold text-signal border border-signal/30 rounded hover:bg-signal/5 transition"
            >
              Today
            </button>
          )}
          <h3 className="font-semibold text-gray-900 whitespace-nowrap">
            {displayMonday.toLocaleDateString('en-US', { month: 'long', year: 'numeric' })} —
            Week of {displayMonday.toLocaleDateString('en-US', { month: 'short', day: 'numeric' })}
          </h3>
          <button
            onClick={handleNextWeek}
            className="px-2 py-1 text-gray-400 hover:text-gray-600 hover:bg-gray-100 rounded font-semibold transition"
          >
            →
          </button>
          <input
            type="date"
            className="px-2 py-1 text-sm border rounded-lg text-gray-600"
            onChange={(e) => {
              if (e.target.value) {
                const picked = new Date(e.target.value + 'T12:00:00')
                const mondayOfPicked = new Date(picked)
                mondayOfPicked.setDate(picked.getDate() - ((picked.getDay() + 6) % 7))
                const diffDays = Math.round((mondayOfPicked.getTime() - monday.getTime()) / (1000 * 60 * 60 * 24))
                setWeekOffset(Math.round(diffDays / 7))
              }
            }}
            title="Jump to date"
          />
        </div>
        <div className="flex gap-1">
          {(['week', 'day', 'list'] as const).map((v) => (
            <button
              key={v}
              onClick={() => setView(v)}
              className={`px-3 py-1.5 text-sm rounded-lg capitalize ${
                view === v
                  ? 'bg-signal text-fg-on-accent'
                  : 'bg-gray-100 text-gray-600 hover:bg-gray-200'
              }`}
            >
              {v}
            </button>
          ))}
        </div>
      </div>

      {/* Crew availability summary */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        <div className="bg-white rounded-xl border p-4">
          <p className="text-xs text-gray-500 uppercase font-semibold">Today&apos;s Deliveries</p>
          <p className="text-2xl font-semibold text-signal mt-1">{todayDeliveries}</p>
          <p className="text-xs text-gray-400 mt-1">
            {todayEntries.length > 0 ? `${todayEntries.length} total entries` : 'No entries'}
          </p>
        </div>
        <div className="bg-white rounded-xl border p-4">
          <p className="text-xs text-gray-500 uppercase font-semibold">Today&apos;s Installs</p>
          <p className="text-2xl font-semibold text-data-positive mt-1">{todayInstalls}</p>
          <p className="text-xs text-gray-400 mt-1">
            {todayEntries.filter((e) => e.entryType === 'INSTALLATION').length} installs assigned
          </p>
        </div>
        <div className="bg-white rounded-xl border p-4">
          <p className="text-xs text-gray-500 uppercase font-semibold">This Week</p>
          <p className="text-2xl font-semibold text-signal mt-1">{weekDeliveries + weekInstalls}</p>
          <p className="text-xs text-gray-400 mt-1">
            {weekDeliveries} deliveries, {weekInstalls} installs
          </p>
        </div>
        <div className="bg-white rounded-xl border p-4">
          <p className="text-xs text-gray-500 uppercase font-semibold">Active Crews</p>
          <p className="text-2xl font-semibold text-gray-900 mt-1">{crews.length}</p>
          <p className="text-xs text-gray-400 mt-1">
            {crewSummaries.reduce((sum, c) => sum + c.count, 0)} entries assigned
          </p>
        </div>
      </div>

      {/* Crew cards */}
      {crewSummaries.length > 0 && (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-3">
          {crewSummaries.map((crew) => (
            <div
              key={crew.name}
              className="bg-gradient-to-br from-blue-50 to-blue-100 rounded-lg border border-blue-200 p-3"
            >
              <p className="text-sm font-semibold text-signal">{crew.name}</p>
              <p className="text-xs text-gray-600 mb-2">{crew.crewType}</p>
              <p className="text-2xl font-semibold text-signal">{crew.count}</p>
              <p className="text-xs text-gray-500">entries this week</p>
            </div>
          ))}
        </div>
      )}

      {error && (
        <div className="bg-red-50 border border-red-200 rounded-xl p-4 text-red-800">
          <p className="font-medium">Error loading schedule</p>
          <p className="text-sm">{error}</p>
        </div>
      )}

      {/* Calendar grid */}
      {view === 'week' && (
        <div className="bg-white rounded-xl border overflow-hidden">
          {/* Day headers */}
          <div className="grid grid-cols-6 border-b">
            {weekDates.map((d) => (
              <div
                key={d.day}
                className={`text-center py-4 border-r last:border-r-0 ${
                  d.isToday ? 'bg-signal/10' : 'bg-gray-50'
                }`}
              >
                <p className="text-xs text-gray-500 uppercase font-semibold">{d.day}</p>
                <p
                  className={`text-lg font-semibold ${
                    d.isToday ? 'text-signal' : 'text-gray-900'
                  }`}
                >
                  {d.date}
                </p>
                <p className="text-xs text-gray-400">{d.month}</p>
              </div>
            ))}
          </div>

          {/* Time slots */}
          {entries.length > 0 ? (
            <div>
              {HOURS.map((hour) => (
                <div key={hour} className="grid grid-cols-6 border-b last:border-b-0 min-h-20">
                  {weekDates.map((d, dayIndex) => {
                    const hourNum = parseInt(hour.split(' ')[0])
                    const slotEntries = getEntriesForSlot(d.fullDate, hourNum)

                    return (
                      <div
                        key={`${hour}-${dayIndex}`}
                        className={`border-r last:border-r-0 px-1 py-1 hover:bg-row-hover cursor-pointer ${
                          d.isToday ? 'bg-signal/[0.02]' : ''
                        }`}
                      >
                        {dayIndex === 0 && (
                          <span className="text-[10px] text-gray-400 font-medium">{hour}</span>
                        )}
                        <div className="space-y-1 mt-1">
                          {slotEntries.map((entry) => {
                            const bgColor = ENTRY_TYPE_COLORS[entry.entryType] || '#9CA3AF'
                            const statusConfig = STATUS_CONFIG[entry.status] || STATUS_CONFIG.FIRM

                            return (
                              <div
                                key={entry.id}
                                onClick={(e) => { e.stopPropagation(); handleEntryClick(entry) }}
                                className={`text-[10px] px-2 py-1 rounded border-2 ${statusConfig.border} text-white font-semibold truncate cursor-pointer hover:opacity-80 transition-opacity`}
                                style={{ backgroundColor: bgColor }}
                                title={`${entry.title} - ${entry.job?.jobAddress || 'No address'}`}
                              >
                                <span className="inline-block mr-1">{statusConfig.icon}</span>
                                {entry.title.substring(0, 10)}
                              </div>
                            )
                          })}
                        </div>
                      </div>
                    )
                  })}
                </div>
              ))}
            </div>
          ) : (
            <div className="border-t">
              <EmptyState
                icon={<CalendarDays className="w-8 h-8 text-fg-subtle" />}
                title="Nothing on the schedule"
                description="Deliveries and installs will appear on the calendar as jobs are scheduled."
              />
            </div>
          )}
        </div>
      )}

      {/* List view */}
      {view === 'list' && entries.length > 0 && (
        <div className="bg-white rounded-xl border overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead className="bg-gray-50 border-b">
                <tr>
                  <th className="px-4 py-3 text-left text-xs font-semibold text-gray-600">Type</th>
                  <th className="px-4 py-3 text-left text-xs font-semibold text-gray-600">Title</th>
                  <th className="px-4 py-3 text-left text-xs font-semibold text-gray-600">Date</th>
                  <th className="px-4 py-3 text-left text-xs font-semibold text-gray-600">Time</th>
                  <th className="px-4 py-3 text-left text-xs font-semibold text-gray-600">Crew</th>
                  <th className="px-4 py-3 text-left text-xs font-semibold text-gray-600">Location</th>
                  <th className="px-4 py-3 text-left text-xs font-semibold text-gray-600">Status</th>
                </tr>
              </thead>
              <tbody>
                {entries.map((entry) => (
                  <tr key={entry.id} onClick={() => handleEntryClick(entry)} className="border-b hover:bg-row-hover cursor-pointer">
                    <td className="px-4 py-3 text-sm">
                      <span
                        className="inline-block px-2 py-1 rounded text-white text-xs font-semibold"
                        style={{ backgroundColor: ENTRY_TYPE_COLORS[entry.entryType] }}
                      >
                        {entry.entryType}
                      </span>
                    </td>
                    <td className="px-4 py-3 text-sm font-medium text-gray-900">{entry.title}</td>
                    <td className="px-4 py-3 text-sm text-gray-600">
                      {new Date(entry.scheduledDate).toLocaleDateString('en-US', {
                        month: 'short',
                        day: 'numeric',
                      })}
                    </td>
                    <td className="px-4 py-3 text-sm text-gray-600">{entry.scheduledTime}</td>
                    <td className="px-4 py-3 text-sm text-gray-600">{entry.crew?.name || 'Unassigned'}</td>
                    <td className="px-4 py-3 text-sm text-gray-600">{entry.job?.jobAddress || 'No address'}</td>
                    <td className="px-4 py-3 text-sm">
                      <span
                        className={`inline-block px-2 py-1 rounded text-xs font-semibold border-2 ${
                          STATUS_CONFIG[entry.status]?.border
                        }`}
                      >
                        {entry.status}
                      </span>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {view === 'list' && entries.length === 0 && (
        <div className="bg-white rounded-xl border overflow-hidden">
          <EmptyState
            icon={<CalendarDays className="w-8 h-8 text-fg-subtle" />}
            title="Nothing on the schedule"
            description="Schedule deliveries and installs to see them listed here with route details."
          />
        </div>
      )}

      {/* Day view */}
      {view === 'day' && (
        <div className="bg-white rounded-xl border overflow-hidden">
          <div className="border-b bg-gray-50 p-4">
            <p className="text-lg font-semibold text-gray-900">
              {today.toLocaleDateString('en-US', {
                weekday: 'long',
                month: 'long',
                day: 'numeric',
              })}
            </p>
          </div>
          {todayEntries.length > 0 ? (
            <div className="divide-y">
              {todayEntries.map((entry) => (
                <div key={entry.id} onClick={() => handleEntryClick(entry)} className="p-4 hover:bg-row-hover cursor-pointer">
                  <div className="flex items-start justify-between">
                    <div>
                      <p className="font-semibold text-gray-900">{entry.title}</p>
                      <p className="text-sm text-gray-600 mt-1">{entry.job?.jobAddress || 'No address'}</p>
                      <p className="text-xs text-gray-500 mt-1">
                        {entry.crew?.name || 'Unassigned'} • {entry.job?.builderName || 'Unknown builder'}
                      </p>
                    </div>
                    <div className="text-right">
                      <div className="flex gap-2">
                        <span
                          className="inline-block px-2 py-1 rounded text-white text-xs font-semibold"
                          style={{ backgroundColor: ENTRY_TYPE_COLORS[entry.entryType] }}
                        >
                          {entry.entryType}
                        </span>
                        <span className="text-sm font-semibold text-gray-900">
                          {entry.scheduledTime}
                        </span>
                      </div>
                      <span className="text-xs text-gray-500 mt-2 block">{entry.status}</span>
                    </div>
                  </div>
                  {entry.notes && (
                    <p className="text-sm text-gray-600 mt-3 pt-3 border-t">{entry.notes}</p>
                  )}
                </div>
              ))}
            </div>
          ) : (
            <EmptyState
              icon={<CalendarDays className="w-8 h-8 text-fg-subtle" />}
              title="Nothing on the schedule"
              description="No deliveries or installs scheduled for today."
            />
          )}
        </div>
      )}

      <CreateScheduleModal
        isOpen={isCreateModalOpen}
        onClose={() => setIsCreateModalOpen(false)}
        onSuccess={fetchData}
      />

      <ScheduleEntryModal
        isOpen={!!selectedEntryId}
        entryId={selectedEntryId}
        onClose={() => setSelectedEntryId(null)}
        onUpdate={fetchData}
      />
    </div>
  )
}
